const PLAYS = [
  {
    id: "i-diki",
    titleGr: "Η Δίκη",
    titleEn: "The Trial",
    author: "Φραντς Κάφκα",
    authorEn: "Franz Kafka",
    director: "Άρης Μπινιάρης",
    year: 2025,
    season: "2025–2026",
    venue: "Θέατρο ARK",
    venueAddress: "Δροσοπούλου 197, Κυψέλη",
    genre: ["Θέατρο", "Κλασικό"],
    duration: "~110'",
    image: "https://www.newsbeast.gr/files/1/2025/09/DIKH2.jpg",
    imageFallback: "https://www.newsbeast.gr/files/1/2025/09/DIKH1.jpg",
    description:
      "Ο Ιωσήφ Κ. ξυπνά ένα πρωί και συλλαμβάνεται χωρίς να του αποκαλυφθεί η κατηγορία. Μπροστά του ξεδιπλώνεται ένα σύστημα αδιαπέραστο, απρόσωπο και παράλογο, που αλέθει τον άνθρωπο σαν βιομηχανική μηχανή. Η διασκευή του Άρη Μπινιάρη μετατρέπει το κλασικό μυθιστόρημα σε ψυχαναλυτικό θρίλερ με καυστικό χιούμορ και σαρωτική σκηνική ενέργεια.",
    cast: [
      { name: "Οδυσσέας Παπασπηλιόπουλος", role: "Ιωσήφ Κ." },
      { name: "Εβίτα Αγαΐτση", role: "" },
      { name: "Αλέξης Βιδαλάκης", role: "" },
      { name: "Αγγελική Δεληθανάση", role: "" },
      { name: "Βασίλης Καζής", role: "" },
      { name: "Κωνσταντίνος Μαγκλάρας", role: "" },
      { name: "Κλέαρχος Παπαγεωργίου", role: "" },
      { name: "Στέφανος Πίττας", role: "" },
      { name: "Σωτήρης Τσακομίδης", role: "" },
      { name: "Νικόλας Χατζηβασιλειάδης", role: "" },
      { name: "Κώστας Phoenix", role: "" },
    ],
    crew: [
      { role: "Σκηνοθεσία & Διασκευή", name: "Άρης Μπινιάρης" },
      { role: "Μετάφραση", name: "Γιάννης Βαλούρδος" },
      { role: "Δραματουργία", name: "Σοφία Ευτυχιάδου" },
      { role: "Μουσική", name: "Jeff Wagner" },
      { role: "Χορογραφία", name: "Αλέξανδρος Σταυρόπουλος" },
      { role: "Φωτογραφία", name: "Ελίνα Γκιουνανλί" },
    ],
    schedule: "Τετ 20:00 / Πεμ–Παρ 21:00 / Σαβ 18:00 & 21:00 / Κυρ 20:00",
    moreUrl: "https://www.more.com/gr-el/tickets/theater/i-diki-tou-kafka/",
    highlight: "Sold out για έναν ολόκληρο χρόνο – επιστρέφει Οκτώβριο 2026",
  },
  {
    id: "oidipodas",
    titleGr: "Οιδίποδας",
    titleEn: "Oedipus",
    author: "Σοφοκλής",
    authorEn: "Sophocles",
    director: "Robert Icke",
    year: 2025,
    season: "2025–2026",
    venue: "Στέγη Ιδρύματος Ωνάση",
    venueAddress: "Λεωφόρος Συγγρού 107–109, Αθήνα",
    genre: ["Αρχαία Τραγωδία", "Σύγχρονη Διασκευή"],
    duration: "~140'",
    image:
      "https://cosmopoliti.com/wp-content/uploads/2025/11/Oedipus_Poster.jpg",
    imageFallback:
      "https://cosmopoliti.com/wp-content/uploads/2025/11/Robert-Icke_Oedipus-©-Yiorgos-Kaplanidis-for-Onassis-Stegi.jpg",
    description:
      "Ο βραβευμένος με Olivier βρετανός σκηνοθέτης Robert Icke μεταμορφώνει τη σοφόκλεια τραγωδία σε ένα σκοτεινό πολιτικό-οικογενειακό θρίλερ. Ο Οιδίποδας, σύγχρονος ηγέτης που επιζητά την αλήθεια πάση θυσία, βρίσκεται να αντιμετωπίζει το αδύνατο: ότι η ίδια η αλήθεια τον καταστρέφει. Η παράσταση μεταφέρθηκε από το Internationaal Theater Amsterdam, με ελληνικό θίασο για πρώτη φορά.",
    cast: [
      { name: "Νίκος Κουρής", role: "Οιδίποδας" },
      { name: "Καρυοφυλλιά Καραμπέτη", role: "Ιοκάστη" },
      { name: "Λάζαρος Γεωργακόπουλος", role: "Κρέοντας" },
      { name: "Ράνια Οικονομίδου", role: "Μερόπη" },
      { name: "Κώστας Νικούλης", role: "" },
      { name: "Σωκράτης Πατσίκας", role: "" },
      { name: "Τάκης Σακελλαρίου", role: "" },
      { name: "Χαρά Γιώτα", role: "" },
      { name: "Γιώργος Ζιάκας", role: "" },
      { name: "Γιάννης Τσουμαράκης", role: "" },
      { name: "Δανάη-Αρσενία Φιλίδου", role: "" },
    ],
    crew: [
      { role: "Σκηνοθεσία", name: "Robert Icke" },
      { role: "Συσκηνοθεσία (ελληνική εκδοχή)", name: "Πρόδρομος Τσινικόρης" },
      { role: "Μετάφραση", name: "Νίκος Χατζόπουλος" },
      { role: "Σκηνογραφία & Κοστούμια", name: "Hildegard Bechtler" },
      { role: "Φωτογραφία", name: "Γιώργος Καπλανίδης" },
    ],
    schedule: "Πεμ–Παρ–Σαβ 20:30 / Κυρ 14:00 (matinée)",
    moreUrl: "https://www.more.com/gr-en/tickets/theatre/",
    highlight: "Olivier Award winner · Sold out για μήνες στη Στέγη",
  },
];
