const PLAYS = [
  {
    id: "i-diki",
    titleGr: "Η Δίκη",
    titleEn: "The Trial",
    author: "Φραντς Κάφκα",
    authorEn: "Franz Kafka",
    director: "Άρης Μπινιάρης",
    year: 2025,
    season: "2025–2026",
    venue: "Θέατρο ARK",
    venueAddress: "Δροσοπούλου 197, Κυψέλη",
    genre: ["Θέατρο", "Κλασικό"],
    duration: "~110'",
    image: "https://www.newsbeast.gr/files/1/2025/09/DIKH2.jpg",
    imageFallback: "https://www.newsbeast.gr/files/1/2025/09/DIKH1.jpg",
    description:
      "Ο Ιωσήφ Κ. ξυπνά ένα πρωί και συλλαμβάνεται χωρίς να του αποκαλυφθεί η κατηγορία. Μπροστά του ξεδιπλώνεται ένα σύστημα αδιαπέραστο, απρόσωπο και παράλογο, που αλέθει τον άνθρωπο σαν βιομηχανική μηχανή. Η διασκευή του Άρη Μπινιάρη μετατρέπει το κλασικό μυθιστόρημα σε ψυχαναλυτικό θρίλερ με καυστικό χιούμορ και σαρωτική σκηνική ενέργεια.",
    cast: [
      { name: "Οδυσσέας Παπασπηλιόπουλος", role: "Ιωσήφ Κ." },
      { name: "Εβίτα Αγαΐτση", role: "" },
      { name: "Αλέξης Βιδαλάκης", role: "" },
      { name: "Αγγελική Δεληθανάση", role: "" },
      { name: "Βασίλης Καζής", role: "" },
      { name: "Κωνσταντίνος Μαγκλάρας", role: "" },
      { name: "Κλέαρχος Παπαγεωργίου", role: "" },
      { name: "Στέφανος Πίττας", role: "" },
      { name: "Σωτήρης Τσακομίδης", role: "" },
      { name: "Νικόλας Χατζηβασιλειάδης", role: "" },
      { name: "Κώστας Phoenix", role: "" },
    ],
    crew: [
      { role: "Σκηνοθεσία & Διασκευή", name: "Άρης Μπινιάρης" },
      { role: "Μετάφραση", name: "Γιάννης Βαλούρδος" },
      { role: "Δραματουργία", name: "Σοφία Ευτυχιάδου" },
      { role: "Μουσική", name: "Jeff Wagner" },
      { role: "Χορογραφία", name: "Αλέξανδρος Σταυρόπουλος" },
      { role: "Φωτογραφία", name: "Ελίνα Γκιουνανλί" },
    ],
    schedule: "Τετ 20:00 / Πεμ–Παρ 21:00 / Σαβ 18:00 & 21:00 / Κυρ 20:00",
    moreUrl: "https://www.more.com/gr-el/tickets/theater/i-diki-tou-kafka/",
    highlight: "Sold out για έναν ολόκληρο χρόνο – επιστρέφει Οκτώβριο 2026",
  },
  {
    id: "oidipodas",
    titleGr: "Οιδίποδας",
    titleEn: "Oedipus",
    author: "Σοφοκλής",
    authorEn: "Sophocles",
    director: "Robert Icke",
    year: 2025,
    season: "2025–2026",
    venue: "Στέγη Ιδρύματος Ωνάση",
    venueAddress: "Λεωφόρος Συγγρού 107–109, Αθήνα",
    genre: ["Αρχαία Τραγωδία", "Σύγχρονη Διασκευή"],
    duration: "~140'",
    image:
      "https://cosmopoliti.com/wp-content/uploads/2025/11/Oedipus_Poster.jpg",
    imageFallback:
      "https://cosmopoliti.com/wp-content/uploads/2025/11/Robert-Icke_Oedipus-©-Yiorgos-Kaplanidis-for-Onassis-Stegi.jpg",
    description:
      "Ο βραβευμένος με Olivier βρετανός σκηνοθέτης Robert Icke μεταμορφώνει τη σοφόκλεια τραγωδία σε ένα σκοτεινό πολιτικό-οικογενειακό θρίλερ. Ο Οιδίποδας, σύγχρονος ηγέτης που επιζητά την αλήθεια πάση θυσία, βρίσκεται να αντιμετωπίζει το αδύνατο: ότι η ίδια η αλήθεια τον καταστρέφει. Η παράσταση μεταφέρθηκε από το Internationaal Theater Amsterdam, με ελληνικό θίασο για πρώτη φορά.",
    cast: [
      { name: "Νίκος Κουρής", role: "Οιδίποδας" },
      { name: "Καρυοφυλλιά Καραμπέτη", role: "Ιοκάστη" },
      { name: "Λάζαρος Γεωργακόπουλος", role: "Κρέοντας" },
      { name: "Ράνια Οικονομίδου", role: "Μερόπη" },
      { name: "Κώστας Νικούλης", role: "" },
      { name: "Σωκράτης Πατσίκας", role: "" },
      { name: "Τάκης Σακελλαρίου", role: "" },
      { name: "Χαρά Γιώτα", role: "" },
      { name: "Γιώργος Ζιάκας", role: "" },
      { name: "Γιάννης Τσουμαράκης", role: "" },
      { name: "Δανάη-Αρσενία Φιλίδου", role: "" },
    ],
    crew: [
      { role: "Σκηνοθεσία", name: "Robert Icke" },
      { role: "Συσκηνοθεσία (ελληνική εκδοχή)", name: "Πρόδρομος Τσινικόρης" },
      { role: "Μετάφραση", name: "Νίκος Χατζόπουλος" },
      { role: "Σκηνογραφία & Κοστούμια", name: "Hildegard Bechtler" },
      { role: "Φωτογραφία", name: "Γιώργος Καπλανίδης" },
    ],
    schedule: "Πεμ–Παρ–Σαβ 20:30 / Κυρ 14:00 (matinée)",
    moreUrl: "https://www.more.com/gr-en/tickets/theatre/",
    highlight: "Olivier Award winner · Sold out για μήνες στη Στέγη",
  },
  {
    id: "antigoni",
    titleGr: "Αντιγόνη",
    titleEn: "Antigone",
    author: "Ζαν Ανούιγ / Σοφοκλής",
    authorEn: "Jean Anouilh / Sophocles",
    director: "Γιώργος Κουτλής",
    year: 2026,
    season: "2025–2026",
    venue: "Κιβωτός",
    venueAddress: "Πειραιώς 115, Γκάζι",
    genre: ["Δράμα", "Κλασικό"],
    duration: "~90'",
    image: "images/antigoni.jpg",
    imageFallback: "https://www.athinorama.gr/Content/ImagesDatabase/p/500x600/crop/both/23/237c7291f6894e6b8e7d01a8d5f9a259.jpg",
    description:
      "Η αναγκαιότητα της αντίστασης απέναντι στον κυνισμό και την απάθεια της εποχής μας. Μέσα από τη διασκευή του Ανούιγ και την τραγωδία του Σοφοκλή, είκοσι νέοι ηθοποιοί δημιουργούν ένα ζωντανό πεδίο σύγκρουσης ιδεών, γενεών και αξιών.",
    cast: [
      { name: "Ιωάννα Αλί", role: "" },
      { name: "Νίκος Αποστολόπουλος", role: "" },
      { name: "Ευαγγελία Κυργιώτη", role: "" },
      { name: "Νεφέλη Παντερμαλή", role: "" },
      { name: "Παύλος Παυλίδης", role: "" },
      { name: "Εύα Τζανακάκη", role: "" },
    ],
    crew: [
      { role: "Σκηνοθεσία", name: "Γιώργος Κουτλής" },
    ],
    schedule: "Παρ–Σαβ 21:00 / Κυρ 20:00",
    moreUrl: "https://www.more.com/gr-el/search/?q=Αντιγόνη",
    highlight: "",
  },
  {
    id: "bussinokipos",
    titleGr: "Ο Βυσσινόκηπος",
    titleEn: "The Cherry Orchard",
    author: "Άντον Τσέχοφ",
    authorEn: "Anton Chekhov",
    director: "Έκτορας Λυγίζος",
    year: 2026,
    season: "2025–2026",
    venue: "Εθνικό Θέατρο",
    venueAddress: "Αγ. Κωνσταντίνου 22–24, Κέντρο",
    genre: ["Δράμα", "Κλασικό"],
    duration: "~130'",
    image: "images/bussinokipos.jpg",
    imageFallback: "https://www.athinorama.gr/Content/ImagesDatabase/p/500x600/crop/both/3e/3ea35987240b4fcd8abf82df4b8b2351.jpg",
    description:
      "Μια τραγικοκωμωδία που εξερευνά τον αγώνα του ανθρώπου ενάντια στο υπαρξιακό κενό. Μια οικογένεια επανενώνεται στο υποθηκευμένο κτήμα της, παγιδευμένη ανάμεσα σε νοσταλγικές αναμνήσεις και ένα αβέβαιο μέλλον, ανίκανη να αποδεχτεί τις αλλαγές.",
    cast: [
      { name: "Έκτορας Λυγίζος", role: "" },
      { name: "Αμαλία Μουτούση", role: "" },
      { name: "Σοφία Κόκκαλη", role: "" },
      { name: "Υβόννη Μαλτέζου", role: "" },
      { name: "Ράνια Οικονομίδου", role: "" },
      { name: "Γιώργος Κλίνης", role: "" },
      { name: "Κατερίνα Πατσιάνη", role: "" },
      { name: "Φώτης Συμεωνίδης", role: "" },
      { name: "Μαρία Μοσχούρη", role: "" },
      { name: "Γιώργος Ζιάκας", role: "" },
      { name: "Γιώργος Παπαδόπουλος", role: "" },
    ],
    crew: [
      { role: "Σκηνοθεσία & Διασκευή", name: "Έκτορας Λυγίζος" },
    ],
    schedule: "Πεμ–Σαβ 20:00 / Κυρ & Τετ 18:00",
    moreUrl: "https://www.more.com/gr-el/search/?q=Βυσσινόκηπος",
    highlight: "Εθνικό Θέατρο · Πρεμιέρα Μάιος 2026",
  },
  {
    id: "theos-tis-sfagis",
    titleGr: "Ο Θεός της Σφαγής",
    titleEn: "God of Carnage",
    author: "Γιασμίνα Ρεζά",
    authorEn: "Yasmina Reza",
    director: "Ζωή Τζουμάκα & Χριστίνα Χριστοφή",
    year: 2026,
    season: "2025–2026",
    venue: "Studio Μαυρομιχάλη",
    venueAddress: "Μαυρομιχάλη 134, Εξάρχεια",
    genre: ["Κωμωδία", "Δράμα"],
    duration: "~80'",
    image: "images/theos-tis-sfagis.jpg",
    imageFallback: "https://www.athinorama.gr/Content/ImagesDatabase/p/500x600/crop/both/cb/cbd6298b1ab744e795c594c4e58abedf.jpg",
    description:
      "Όταν ο Φερδινάνδος χτυπάει τον συμμαθητή του Μπρούνο, οι γονείς τους συναντώνται. Τα βίαια ένστικτα ξεπροβάλλουν καθώς η πολιτισμένη συζήτηση μεταμορφώνεται σε βάναυση σύγκρουση. Οι κοινωνικές μάσκες πέφτουν, η συμπεριφορική ευγένεια θρυμματίζεται, απελευθερώνοντας χάος.",
    cast: [
      { name: "Ευαγγελία Καπόγιαννη", role: "" },
      { name: "Μαρία Μπρανίδου", role: "" },
      { name: "Βασίλης Πουλάκος", role: "" },
      { name: "Δημήτρης Φίλιππας", role: "" },
    ],
    crew: [
      { role: "Σκηνοθεσία", name: "Ζωή Τζουμάκα & Χριστίνα Χριστοφή" },
      { role: "Μετάφραση", name: "Γιώργος Αρχιμανδρίτης" },
      { role: "Σκηνογραφία", name: "Ισιδώρα Ντούλου" },
    ],
    schedule: "Σαβ 18:00",
    moreUrl: "https://www.more.com/gr-el/search/?q=Θεός+σφαγής",
    highlight: "",
  },
  {
    id: "macbeth",
    titleGr: "Μάκβεθ",
    titleEn: "Macbeth",
    author: "Ουίλιαμ Σαίξπηρ",
    authorEn: "William Shakespeare",
    director: "Παναγιώτης Εξαρχέας",
    year: 2026,
    season: "2025–2026",
    venue: "Από Μηχανής Θέατρο",
    venueAddress: "Ακαδήμου 13, Μεταξουργείο",
    genre: ["Δράμα", "Κλασικό"],
    duration: "~100'",
    image: "images/macbeth.jpg",
    imageFallback: "https://www.athinorama.gr/Content/ImagesDatabase/p/500x600/crop/both/5e/5e1f0f50c0574874a7e57de75894becd.jpg",
    description:
      "Μια σύγχρονη ερμηνεία όπου τέσσερις άνδρες ηθοποιοί ανεβάζουν ένα βίαιο 'παιχνίδι ενηλικίωσης', μετατρέποντας τη σκηνή σε πεδίο εξερεύνησης των ανθρώπινων ορίων και της σχέσης του αρσενικού υποκειμένου με την εξουσία.",
    cast: [
      { name: "Βασίλης Αμπατζής", role: "" },
      { name: "Θοδωρής Ζερίτης", role: "" },
      { name: "Άρης Μπαλής", role: "" },
      { name: "Γιώργος Χριστοδούλου", role: "" },
    ],
    crew: [
      { role: "Σκηνοθεσία", name: "Παναγιώτης Εξαρχέας" },
    ],
    schedule: "Πεμ–Σαβ 21:00 / Κυρ 18:15",
    moreUrl: "https://www.more.com/gr-el/search/?q=Μάκβεθ",
    highlight: "",
  },
  {
    id: "12-enorkoi",
    titleGr: "Οι 12 Ένορκοι",
    titleEn: "12 Angry Jurors",
    author: "Ρέτζιναλντ Ρόουζ",
    authorEn: "Reginald Rose",
    director: "Κώστας Νικολαΐδης",
    year: 2025,
    season: "2025–2026",
    venue: "Θέατρο Αλκμήνη",
    venueAddress: "Αλκμήνης 12, Πετράλωνα",
    genre: ["Δράμα", "Κλασικό"],
    duration: "~105'",
    image: "images/12-enorkoi.jpg",
    imageFallback: "https://www.athinorama.gr/Content/ImagesDatabase/p/500x600/crop/both/3a/3a3af75e20874fbcb97c227ba2bc7318.jpg",
    description:
      "Δώδεκα ένορκοι πρέπει να αποφασίσουν ομόφωνα για τη μοίρα ενός 16χρονου μετανάστη που κατηγορείται για πατροκτονία στη Νέα Υόρκη του 1957. Κοινωνικές προκαταλήψεις, ψυχολογικά πορτραίτα και η αγωνία της δικαιοσύνης σε έναν κλειστό χώρο όπου η θανατική ποινή είναι υποχρεωτική.",
    cast: [
      { name: "Τάσος Γιαννόπουλος", role: "" },
      { name: "Μάνος Ζαχαράκος", role: "" },
      { name: "Ορέστης Τρίκας", role: "" },
      { name: "Αντώνης Βαρθαλίτης", role: "" },
      { name: "Πέτρος Ράντλ", role: "" },
      { name: "Αλέξανδρος Καλπακίδης", role: "" },
    ],
    crew: [
      { role: "Σκηνοθεσία", name: "Κώστας Νικολαΐδης" },
      { role: "Σκηνογραφία", name: "Δημήτρης Νεγκρίν" },
      { role: "Κοστούμια", name: "Κατερίνα Μήλιου" },
      { role: "Μουσική", name: "Γιώργος Οικονόμου" },
    ],
    schedule: "Πεμ–Σαβ 21:30 / Κυρ 18:00",
    moreUrl: "https://www.more.com/gr-el/search/?q=12+ένορκοι",
    highlight: "",
  },
  {
    id: "alexandria",
    titleGr: "Αλεξάνδρεια",
    titleEn: "Alexandria",
    author: "Ζέτη Φίτσιου",
    authorEn: "Zeti Fitsiou",
    director: "Φοίβος Ευαγγελινός",
    year: 2025,
    season: "2025–2026",
    venue: "Θέατρο Παλλάς",
    venueAddress: "Βουκουρεστίου 5 (City Link), Κέντρο",
    genre: ["Δράμα", "Μιούζικαλ"],
    duration: "~150'",
    image: "images/alexandria.jpg",
    imageFallback: "https://www.athinorama.gr/Content/ImagesDatabase/p/500x600/crop/both/94/941452dafe7243ff83efa3c2741b5d17.jpg",
    description:
      "Η Άννα, διάσημη Αθηναία ηθοποιός των '60s, αντιμετωπίζει το παρελθόν της όταν μια νεαρή δημοσιογράφος την επισκέπτεται. Ένα ξεχασμένο βιβλίο πυροδοτεί αναμνήσεις από την Αλεξάνδρεια του '30, όπου τίποτα δεν είναι όπως φαίνεται. Ταξικές διαιρέσεις, κοινωνικές εντάσεις και μια απαγορευμένη ερωτική ιστορία.",
    cast: [
      { name: "Άννα Μάσχα", role: "" },
      { name: "Ερασμία Μανούρη", role: "" },
      { name: "Ιωάννης Παπαζήσης", role: "" },
      { name: "Χριστίνα Αλεξανιάν", role: "" },
      { name: "Ελένη Καρακάση", role: "" },
      { name: "Δημήτρης Δεγαΐτης", role: "" },
      { name: "Λουκία Ματσάγγου", role: "" },
      { name: "Γιώργος Ψυχογυιός", role: "" },
    ],
    crew: [
      { role: "Σκηνοθεσία", name: "Φοίβος Ευαγγελινός" },
      { role: "Μουσική", name: "Ευανθία Ρεμπούτσικα" },
      { role: "Στίχοι", name: "Άρης Δαβαράκης" },
      { role: "Σκηνογραφία", name: "Μανόλης Παντελιδάκης" },
      { role: "Κοστούμια", name: "Ιωάννα Τσάμη" },
      { role: "Video Art", name: "Παύλος Μάκκας" },
    ],
    schedule: "Σαβ 15:00 / Κυρ 16:00 / Τετ 19:30",
    moreUrl: "https://www.more.com/gr-el/search/?q=Αλεξάνδρεια",
    highlight: "Θέατρο Παλλάς · Μουσική Ευανθίας Ρεμπούτσικα",
  },
];
